name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Build the Docker Image
        run: |
          sudo docker build -t blakerain/container-copier .
      - name: Login to Docker
        run: |
          sudo docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Image
        run: |
          sudo docker push blakerain/container-copier:latest
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          sudo docker tag blakerain/container-copier:latest blakerain/container-copier:$RELEASE_VERSION
          sudo docker push blakerain/container-copier:$RELEASE_VERSION
