name: Deploy

on:
  push:
    tags:
      - v*

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ gitea.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - run: |
          echo "Checking docker socket"
          ls -la /var/run/docker.sock
          echo "Attempting to run 'docker info'"
          docker info
          echo "Seeing if we need to use 'sudo' to run 'docker info'"
          sudo docker info
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: meta
        name: Extract Metadata for Dockert
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: "{{ defaultContext }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
